Repository wecode-bootcamp-korea/21-1st-Ojusmarket-frontend, pull requests merged in 2021-06, with the labels that each got.

#2 Add : HeaderComponent 레이아웃 구현 완료
  public/images/logo.png
  public/index.html
  src/Component/HeaderComponent/Header.js
  src/Component/HeaderComponent/Header.scss
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: 리뷰 요청

#5 Add : 스타일 변수 저장
  public/index.html
  src/Styles/Common.scss
Labels: Status: Accepted

#10 Fix : variable,mixin.scss추가 및 scss 1차 refactoring
  src/Component/FooterComponent/Footer.scss
  src/Component/HeaderComponent/Header.scss
  src/Pages/Main/Food/Food.js
  src/Pages/Main/Food/Food.scss
  src/Pages/Main/Main.scss
  src/Pages/Main/Recipe/Recipe.js
  src/Pages/Main/Recipe/Recipe.scss
  src/Pages/Main/Recipe/RecipeContent.js
  src/Pages/Main/slider/Slider.js
  src/Pages/Main/slider/Slider.scss
  src/Styles/Common.scss
  src/Styles/Mixin.scss
  src/Styles/Variable.scss
Labels: Status: 리뷰 요청

#7 Add : 상품상세페이지 수정 요청사항 반영 완료
  public/Data/infoData.json
  public/images/ingredient/노랑파프리카.png
  public/images/ingredient/무농약양파.png
  public/images/ingredient/비비쿡처음먹는까망소시지.png
  public/images/ingredient/빨강파프리카.png
  public/images/ingredient/양송이버섯.png
  public/images/ingredient/우리밀고소한백밀가루.png
  public/images/ingredient/유기농먹어봤니토마토바질파스타소스.png
  public/images/ingredient/유기농블루베리.png
  public/images/ingredient/프레지덩무염버터.png
  public/images/recipes/면두부파스타.png
  public/images/recipes/블루베리머핀.png
  public/images/recipes/소시지야채구이.png
  src/Pages/Main/Main.js
  src/Pages/ProductInfo/DetailInfo.js
  src/Pages/ProductInfo/DetailInfo.scss
  src/Pages/ProductInfo/ProductDetail.js
  src/Pages/ProductInfo/ProductDetail.scss
  src/Pages/ProductInfo/ProductInfo.js
  src/Pages/ProductInfo/ProductInfo.scss
  src/Pages/ProductInfo/RelatedList.js
  src/Pages/ProductInfo/RelatedList.scss
  src/Pages/ProductInfo/Reviews.js
  src/Pages/ProductInfo/Reviews.scss
  src/Routes.js
Labels: Status: Accepted

#9 Add : 장바구니 레이아웃, 수량입력, 삭제 구현 완료 상품 선택기능 구현완료
  public/Data/CartData.json
  src/Pages/CartList/CartItem.js
  src/Pages/CartList/CartItem.scss
  src/Pages/CartList/CartList.js
  src/Pages/CartList/CartList.scss
  src/Pages/Main/Main.js
  src/Pages/ProductInfo/ProductDetail.scss
  src/Pages/ProductInfo/ProductInfo.scss
  src/Pages/ProductInfo/Reviews.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#12 Main-Detail페이지 Router기능 추가, 백엔드와 통신 준비중
  public/Data/infoData.json
  src/Component/HeaderComponent/Header.js
  src/Component/HeaderComponent/Header.scss
  src/Pages/CartList/CartList.js
  src/Pages/Main/Food/Food.js
  src/Pages/Main/Food/FoodContent.js
  src/Pages/Main/Main.js
  src/Pages/ProductInfo/ProductInfo.js
  src/Pages/ProductInfo/ProductInfo.scss
  src/Pages/ProductInfo/RelatedList.js
  src/Pages/ProductInfo/RelatedList.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#8 Add: 배송지 레이아웃 업데이트
  public/Data/userData.json
  src/Pages/Delivery/BasicInfo.js
  src/Pages/Delivery/Delivery.js
  src/Pages/Delivery/Delivery.scss
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Pages/purchase/CheckCart.js
  src/Pages/purchase/CheckCart.scss
  src/Pages/purchase/Purchase.js
  src/Pages/purchase/Purchase.scss
  src/Routes.js
  src/Utill/config.js
Labels: Status: 리뷰 요청

#11 Add: 동적라우팅기능 추가 , 폰트 및 로고위치 수정
  public/index.html
  src/Pages/Main/Food/Food.scss
  src/Pages/Main/Food/FoodContent.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/Recipe/Recipe.js
  src/Pages/Main/Recipe/Recipe.scss
  src/Routes.js
  src/Styles/Common.scss
Labels: Status: 리뷰 요청

#14 ADD 로그인 페이지 리팩토링3차완료
  .gitattributes
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Utill/config.js
Labels: Status: 리뷰 요청

#15 ADD 회원가입 페이지 리팩토링 3차완료
  public/images/adlogo.png
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Routes.js
  src/Styles/Mixin.scss
  src/Utill/config.js
  src/Utill/validaters.js
Labels: Status: 리뷰 요청

#16 ADD 요리상세페이지 1차리팩토링 완료
  src/Pages/Main/Recipe/Recipe.js
  src/Pages/Main/Recipe/RecipeContent.js
  src/Pages/RecipeInfo/Cook/Cook.js
  src/Pages/RecipeInfo/Cook/Cook.scss
  src/Pages/RecipeInfo/Product/Product.js
  src/Pages/RecipeInfo/Product/Product.scss
  src/Pages/RecipeInfo/ProductList/ProductList.js
  src/Pages/RecipeInfo/ProductList/ProductList.scss
  src/Pages/RecipeInfo/RecipeInfo.js
  src/Pages/RecipeInfo/RecipeInfo.scss
  src/Pages/RecipeInfo/RecipeList/RecipeList.js
  src/Routes.js
  src/Utill/config.js
Labels: Status: 리뷰 요청

#17 Fix/config 장바구니로에서 결제창으로 데이터 전달하기 구현
  public/Data/CartData.json
  src/Pages/CartList/CartList.js
  src/Pages/Delivery/Delivery.js
  src/Pages/Main/Main.js
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/Pages/purchase/CheckCart.js
  src/Pages/purchase/Purchase.js
Labels: Status: Conflict 해결 요청

#19 ADD 로그인페이지 새브런치생성 및 수정
  src/Pages/Login/Login.js
  src/Utill/config.js
Labels: Status: 리뷰 요청
